### ISSUE TITLE
Test suite failing?

### ISSUE THREAD

**Issue by Diiaablo95** [w3c/did-test-suite#99] opened 2021-05-11 08:06 UTC
I don't know if it's just a problem I have, but I tried cloning the repo, installing the dependencies, and running the test suite that comes with the repo, and the tests are failing.

The error is the following:

```javascript
    TypeError: require(...).didCorePropertiesTests is not a function

      10 |     `5.x Core Properties - ${didMethod} - ${implementation} - ${implementer}`;
      11 |   describe(suiteName, () => {
    > 12 |     require('./did-core-properties').didCorePropertiesTests(
         |                                      ^
      13 |       didMethodSuiteConfig);
      14 |   });
      15 |

      at Suite.<anonymous> (suites/did-core-properties/did-core-properties.spec.js:12:38)
      at forEach (suites/did-core-properties/did-core-properties.spec.js:11:3)
          at Array.forEach (<anonymous>)
      at Object.<anonymous> (suites/did-core-properties/did-core-properties.spec.js:7:24)
```

which happens with each DID method in the Core Properties test suite. I am running `npm run test` from within `did-core-test-server` as instructed in the test README.

Is there any solution to this?

**Comment by caict-develop-zhangbo** [comment] 2021-05-17 10:02
I have the same problem. Is there any solution now？

**Comment by MajdT51** [comment] 2021-05-19 12:49
I have the same problem
![image](https://user-images.githubusercontent.com/50261972/118815251-546bb880-b8b1-11eb-9cf4-75f939640254.png)

**Comment by sondreb** [comment] 2021-05-19 15:42
Based on the errors, I think you have not fully installed the dependencies with lerna.

Make sure you go to root folder, edit the package.json by removing the "--since origin/master" from the "install:ci" script.

Then run

```sh
npm run install:ci
```

Please notice that this is custom script, "install:ci". It is not enough to simply run "npm install".

You should be able to run the test suite from root of repo, and it appears to work fine from within the "did-core-test-server" folder as well.

**Comment by Diiaablo95** [comment] 2021-05-19 15:49
@sondreb by following those very same instructions, the problem still persists (just tried again). My suspicion is that it depends on some local version of some tools/packages I have, but I cannot figure out what. It seems to be that the `require` syntax is working for all the other documents (i.e., they can be imported as objects) but the `./did-core-properties` one, no idea why, as it produces a `{}` empty document, hence the error generated.

**Comment by msporny** [comment] 2021-05-20 14:05
@Diiaablo95 I'm unable to reproduce the errors, I will try again this weekend with your branch to see if there are any errors.

**Comment by BernhardFuchs** [comment] 2021-05-21 08:55
@Diiaablo95 For me the [Dockerfile](https://github.com/w3c/did-test-suite/blob/262f6dc7fd001e6f16f56cdb84e6153bab8eeeed/Dockerfile#L20) was a good reference.  
After running `lerna bootstrap` and `lerna run build` I had no issues.

**Comment by Diiaablo95** [comment] 2021-05-21 09:58
@BernhardFuchs it is getting more and more weird. I seem to be having the same issue, no matter what. It is just weird that `require('./did-core-properties')` returns an empty object `{}` instead of the content of the file.

**Comment by MajdT51** [comment] 2021-05-21 11:51
update: I have also the exact same problem if I just run the tests from the main branch

**Comment by kdenhartog** [comment] 2021-06-01 07:04
I was able to fix once I updated to Node 14.16.1 and ran `lerna bootstrap` and `lerna run build`

**Comment by Diiaablo95** [comment] 2021-06-03 07:43
Ok thanks @kdenhartog, I can confirm that with Node 14(.17.0) the tests are now passing without failing. I was previously running them with Node 12. Perhaps this could be specified somewhere in the README file.

**Comment by kdenhartog** [comment] 2021-06-05 01:37
@Diiaablo95 the packages.json should trigger a warning if something below Node 14 is used once PR #160 is merged

**Comment by kdenhartog** [comment] 2021-06-06 00:08
This has been addressed now and is merged. Closing this issue.

**Closed by kdenhartog** 2021-06-06 00:08 UTC
